name: petalytic
description: "Flutter App for pet's analytics."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/common/

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  ios: true
  android: true
  image_path_ios: "assets/common/app-icon.png"
  image_path_ios_dark_transparent: "assets/common/app-icon-transparent.png"
  image_path_android: "assets/android/app-icon-android.png"
  adaptive_icon_background: "assets/android/app-icon-background.png"
  adaptive_icon_foreground: "assets/android/app-icon-foreground.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/common/app-icon.png"

# Flutter Native Splash configuration
flutter_native_splash:
  color: "#ffffff"
  color_android: "#ffffff"
  color_dark_android: "#121212"
  color_ios: "#ffffff"
  color_dark_ios: "#121212"
  color_web: "#ffffff"
  color_dark_web: "#121212"
  image: "assets/android/app-icon-foreground.png"
  android_12:
    color: "#ffffff"
    icon_background_color: "#FFFFFF"
    image: "assets/android/app-icon-foreground.png"
    color_dark: "#121212"
    icon_background_color_dark: "#121212"
    image_dark: "assets/android/app-icon-foreground.png"