name: petalytic
description: "Flutter App for pet's analytics."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  fl_chart: ^1.1.0
  camera: ^0.11.2
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_flavorizr: ^2.4.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/common/
    - assets/images/

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  ios: true
  android: true
  image_path_ios: "assets/common/app-icon.png"
  image_path_ios_dark_transparent: "assets/common/app-icon-transparent.png"
  image_path_android: "assets/android/app-icon-android.png"
  adaptive_icon_background: "assets/android/app-icon-background.png"
  adaptive_icon_foreground: "assets/android/app-icon-foreground.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/common/app-icon.png"

# Flutter Native Splash configuration
flutter_native_splash:
  color: "#ffffff"
  color_android: "#ffffff"
  color_dark_android: "#121212"
  color_ios: "#ffffff"
  color_dark_ios: "#121212"
  color_web: "#ffffff"
  color_dark_web: "#121212"
  image: "assets/android/app-icon-foreground.png"
  android_12:
    color: "#ffffff"
    icon_background_color: "#FFFFFF"
    image: "assets/android/app-icon-foreground.png"
    color_dark: "#121212"
    icon_background_color_dark: "#121212"
    image_dark: "assets/android/app-icon-foreground.png"


# Flutter Flavorizr
flavorizr:
  ide: "vscode"
  app:
    android:
      flavorDimensions: "flavor-type"
    
  flavors:
    dev:
      app:
        name: "petalytic Dev"
      android:
        applicationId: "com.paulyswen.petalytic.dev"
        icon: "assets/dev/app-icon.png"
        adaptiveIcon:
          foreground: "assets/dev/app-icon-foreground.png"
          background: "assets/android/app-icon-background.png"
      ios:
        bundleId: "com.paulyswen.petalytic.dev"
        icon: "assets/dev/app-icon.png"
    

    stg:
      app:
        name: "petalytic Stg"
      android:
        applicationId: "com.paulyswen.petalytic.stg"  
        icon: "assets/stg/app-icon.png"
        adaptiveIcon:
          foreground: "assets/stg/app-icon-foreground.png"
          background: "assets/android/app-icon-background.png"
      ios:
        bundleId: "com.paulyswen.petalytic.stg"
        icon: "assets/stg/app-icon.png"

    prod:
      app:
        name: "petalytic"
      android:
        applicationId: "com.paulyswen.petalytic"  
        icon: "assets/prod/app-icon.png"
        adaptiveIcon:
          foreground: "assets/prod/app-icon-foreground.png"
          background: "assets/android/app-icon-background.png"
      ios:
        bundleId: "com.paulyswen.petalytic"
        icon: "assets/prod/app-icon.png"